// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6mMB3grBIyqU1DOaN-11n8AbKoVlSx9o',
    appId: '1:744750497412:web:6ad42b15b893cd83c18cd1',
    messagingSenderId: '744750497412',
    projectId: 'flavordev-151c4',
    authDomain: 'flavordev-151c4.firebaseapp.com',
    storageBucket: 'flavordev-151c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOX23t6IE_mPJxV-suOpGV2LCKYBRLIcA',
    appId: '1:744750497412:android:237b20cfe07878e9c18cd1',
    messagingSenderId: '744750497412',
    projectId: 'flavordev-151c4',
    storageBucket: 'flavordev-151c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW7RGanvyi7GcGAhDOscZNMiBYH3ogV-w',
    appId: '1:744750497412:ios:f2f217f8b10b58f2c18cd1',
    messagingSenderId: '744750497412',
    projectId: 'flavordev-151c4',
    storageBucket: 'flavordev-151c4.appspot.com',
    iosBundleId: 'com.example.flavor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW7RGanvyi7GcGAhDOscZNMiBYH3ogV-w',
    appId: '1:744750497412:ios:623787f91ef64984c18cd1',
    messagingSenderId: '744750497412',
    projectId: 'flavordev-151c4',
    storageBucket: 'flavordev-151c4.appspot.com',
    iosBundleId: 'com.example.flavor.RunnerTests',
  );
}
